# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(608, 436)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(" background-color:rgb(236, 255, 184);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_zapis = QtWidgets.QPushButton(self.centralwidget)
        self.start_zapis.setGeometry(QtCore.QRect(210, 250, 181, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.start_zapis.setFont(font)
        self.start_zapis.setStyleSheet("color: rgb(255, 120, 79);\n"
"background-color: rgb(49, 255, 90);\n"
"border: 2pk solid black;\n"
"border-radius: 20px;")
        self.start_zapis.setObjectName("start_zapis")
        self.lbl_inform = QtWidgets.QLabel(self.centralwidget)
        self.lbl_inform.setGeometry(QtCore.QRect(210, 340, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lbl_inform.setFont(font)
        self.lbl_inform.setStyleSheet("color: rgb(0, 129, 71);\n"
"background-color:rgb(0, 200, 194);\n"
"border: 2px solid black;\n"
"border-radius: 20px;")
        self.lbl_inform.setObjectName("lbl_inform")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(110, 10, 391, 161))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("color: rgb(255, 107, 236);\n"
"background-color: rgb(129, 255, 25);\n"
"border: 2px solid black;\n"
"border-radius: 20px;")
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 320, 91, 81))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Снимок экрана 2026-07-05 135412.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 190, 381, 51))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 260, 121, 61))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_zapis.setText(_translate("MainWindow", "Запис"))
        self.lbl_inform.setText(_translate("MainWindow", "         ..."))
        self.pushButton.setText(_translate("MainWindow", "Текст"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
